
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tweet2vk-dev
  username: dev
  password: dev
  host: localhost

test:
  <<: *default
  host: localhost
  database: tweet2vk-test
  username: test
  password: test1

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
